# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f37f1b0d737694ade1f546ee83f301d82e71a77a3163df370fec740fc8fb07e513526ef1e8d0e61bc3901686e3e9bba70380da2e6c1b5db1c160bca053fb301e

test:
  secret_key_base: 9bdb7ece612e3a1081b9d3fa4b74fe18fadcd9a625fd06818a16f16af21d4a92afb501f721cb373a935c01bfb434eac926a4aa30885215d692cdf799f0049cc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
